a = float(input("enter 1st number: "))
b = float(input("enter 2nd number: "))
c = float(input("enter 3srd number: "))
smallest_num = min(a,b,c)
largest_num = max(a,b,c)
print("The smallest number is ", smallest_num)
print("The largest number is ", largest_num)
